[build-system]
requires = ["setuptools", "wheel==0.30.0", "versioneer-518"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=Celeratas"
testpaths = [
    "tests",
]
